GET http://localhost:4000/task

###
POST  http://localhost:4000/task/
Content-Type: application/json

{
    "name":"Amazing ppp",
    "reminder":true,
    "taskDate": "xx"
}

###
GET http://localhost:4000/task/60267fdddcc318592c4cdddb

###
PATCH http://localhost:4000/task/60267fdddcc318592c4cdddb
Content-Type: application/json

{
    "name":"Amazing ppp1",
    "reminder":false,
    "taskDate": "xx1"
}

###
DELETE http://localhost:4000/task/60267fdddcc318592c4cdddb