GET http://localhost:9000/.netlify/functions/server

###
POST  https://brave-murdock-46d903.netlify.app/.netlify/functions/server
Content-Type: application/json

{
    "name":"Amazing ppp",
    "reminder":true,
    "taskDate": "xx"
}

###
GET http://localhost:4000/task/60276feeedf1b7376053dd9f

###
PATCH http://localhost:4000/task/60267fdddcc318592c4cdddb
Content-Type: application/json

{
    "name":"Amazing ppp1",
    "reminder":false,
    "taskDate": "xx1"
}

###
DELETE http://localhost:4000/task/60267fdddcc318592c4cdddb