GET http://localhost:9000/.netlify/functions/server

###
POST  http://localhost:9000/.netlify/functions/server/signup
Content-Type: application/json

{
    "username":"Amazing2",
    "password":"trueqqqqq1111"
}

###
GET http://localhost:9000/.netlify/functions/server/login/
Content-Type: application/json

{
    "username":"Amazing",
    "password":"trueqqqqq1111"
}

###
GET http://localhost:9000/.netlify/functions/server/session/
Content-Type: application/json

{
    "username":"Amazing",
    "token": "ssDaZGDvIMfDCSM5"
}

###
PATCH http://localhost:4000/task/60267fdddcc318592c4cdddb
Content-Type: application/json

{
    "name":"Amazing ppp1",
    "reminder":false,
    "taskDate": "xx1"
}

###
DELETE http://localhost:4000/task/60267fdddcc318592c4cdddb